server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: development
  datasource:
    password: knoxer1403
    url: jdbc:postgresql://localhost:5432/tx
    username: arthu
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tradex.arthur@gmail.com
    password: igsfugwaweebybxn
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# reCAPTCHA
google:
  recaptcha:
    secret: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    url: https://www.google.com/recaptcha/api/siteverify
    threshold: 0.5

# apps env variables
app:
  BASE_URL: http://localhost:8080/

