server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always




spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    initialization-mode: ALWAYS
    url: jdbc:mysql://localhost:3306/ethniconnect?serverTimezone=UTC
    #url: jdbc:mysql://ethniconnectdb.cs03gfixeofo.us-east-2.rds.amazonaws.com:3306/ethniconnect
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

 # mail:
  #  host: smtp.gmail.com
   # port: 587
    #username:
    #password:
    #properties:
      #mail:
        #smtp:
          #auth: true
          #starttls:
            #enable: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ethniconnect@gmail.com
    password: nftvtqgflwntjipb


    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  servlet :
    multipart :
      max-file-size: 15MB
      max-request-size: 15MB
